name: PHP Scheduled Script

on:
  schedule:
    # 每天凌晨 2 点执行
    - cron: '25 6 * * *'

jobs:
  run-php-script:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up PHP
      uses: shivammathur/setuptools@v2
      with:
        php-version: '8.1'  # 可以根据你的需求选择 PHP 版本
    - name: Run PHP script
      run: |
        php your-php-script.php
